name = "MyMath"
uuid = "bf7a08aa-00b9-4905-aaec-97a62dc27935"
authors = ["Bill Crupi <crupib@gmail.com>"]
version = "0.1.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Test = "1.11.0"
